platform :ios, '11.0'
use_frameworks! :linkage => :static


source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.chuanyinet.com:basic-platform/iOS/palm-specs.git'


def base_comps
  pod 'SDWebImage', '5.13.0'
  pod 'SDWebImageWebPCoder', '0.9.1'
  pod 'MBProgressHUD', '1.0.0'
  pod 'MJExtension', '= 3.4.1'
  pod 'Masonry', '1.1.0'
end


def moudle_comps
  pod 'ZCUtils', :path => 'ZCUtils_Pods/'
end


target 'ZCUtilsProject' do
  use_modular_headers!
  
  base_comps
  moudle_comps
end


post_install do |installer|
  #react_native_post_install(installer)
  #__apply_Xcode_12_5_M1_post_install_workaround(installer)
  
  installer.target_installation_results.pod_target_installation_results
  .each do |pod_name, target_installation_result|
    target_installation_result.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= '$(inherited) '
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '"_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION" '
    end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      #config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      #config.build_settings['STRIP_STYLE'] = 'all'
    end
  end
end
